import setuptools

setuptools.setup(
    use_scm_version={
        "write_to": "src/newrelic_airflow_plugin/version.py",
        "write_to_template": """\
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = "{version!s}"
""",
    },
    install_requires=("apache-airflow<2, >=1.8", "newrelic-telemetry-sdk~=0.2"),
)
